language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
  - $HOME/.gradle
  - $HOME/.docker
after_success:
  - ./build-docker.sh --skipGradle
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push fergusstrange/cloudbot-slack-integration
